### ISSUE TITLE
Library not usable in an AngularJS mock scenario

### ISSUE THREAD

**Issue by richard-nkrumah** [uxder/Radio#14]
In an client-side AngularJS Jasmine test, the function "module" is defined via angular-mocks.js. When the code under test uses the radio library, then the library is not properly registered as a global but as a member of this function.
To determine if the code is run in a node.js environment, I suggest to test if the field "angular" is _not_ set, too.

**Comment by uxder** [comment]
I haven't seen this problem.  Do you have an example you can point to?
