### ISSUE TITLE
unsubscribe within subscribe function

### ISSUE THREAD

**Issue by notionslate** [uxder/Radio#16]
My desire is to unsubscribe to a broadcast after the first broadcast, so I put an unsubscribe method at the end of my subscribe function.  This works unless another subscriber is also listening for the same broadcast.  In that case, my subscribe function is called (where it unsubscribes itself), but then, rather than the other subscriber function being called, my subscribe function is called a second time.

Can this behavior be verified?
Is there a better way to do what I'm trying to do?

**Comment by ziogaschr** [comment]
I am also trying to do the same and have a similar behaviour.

**Comment by notionslate** [comment]
Thanks for the second...what I ended up doing was creating a second distinct channel so I know there will only be one subscriber - not ideal, but it does the job.  My guess is that an internal radio array gets 'confused' when a function is removed from the array while it is in the middle of traversing the array to call functions for the channel. Also guessing that if the unsubscribe was called while in the last subscriber function, the problem would not be seen.
