### ISSUE TITLE
Doesn't work in the browser

### ISSUE THREAD

**Issue by andrewplummer** [uxder/Radio#19]

**Comment by uxder** [comment]
Dude Andrew.  It's because you don't know how to code.    

Won't Fix.

**Comment by MehdiRaash** [comment]
Sorry, hey mate **Andrewplummer**, Were you serious? 
Dear **uxder** Were you serious as well?

I'm just saying because it does not seem andrewplummer was offensive.

**Comment by uxder** [comment]
@andrewplummer is my friend who likes to mess with me from time to time....    So this issue is just Andrew messing around :)  Don't worry, it does work in browsers.

**Comment by MehdiRaash** [comment]
Some time ago I clicked on **star button** on this project :-), and also watching as well. 
:-D just got shocked by the message! 
Great, Can I ask you something?

**Comment by uxder** [comment]
@MehdiRaash What's your question?

**Comment by MehdiRaash** [comment]
What does Closure guy mean?
Actually what influenced you to pick this phrase for your title.

**Comment by uxder** [comment]
A friend did that illustration for me because I used to do some work with Google Closure library. :)

**Comment by MehdiRaash** [comment]
I just checked your website, but it's not available.
Were you a blog (Web) writer about coding and something?

**Comment by uxder** [comment]
Ah yeah, I took my site down because I was unhappy with it.  It was just my portfoliio site....nothing all that interesting anyways :)

**Comment by MehdiRaash** [comment]
Good to know.
You as a good programmer, Are you able to manage your time in a really effective and satisfying way?
You know, It's a difficult task, and I just wanted to know, How do you overcome to this issue? 
For sure I assume, you are working in a company or on your own, and having some side projects, and reading some books.

**Comment by uxder** [comment]
@MehdiRaash Haha, did expect so many questions.  Let's offline this if you want to talk about stuff since I don't want to flood this repo with too much non-relevant issues to radio.    Feel free to email me if you want :)

**Comment by MehdiRaash** [comment]
Thanks for your time. you are right, excuse me, I sent an email.
